# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EasyGruaCPAR02' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EasyGruaCPAR02
        pod 'Firebase/Core'
        pod 'FirebaseUI/Auth'
        pod 'Firebase/Database'

        pod 'FirebaseUI/Google'
        pod 'FirebaseUI/Facebook'

        pod 'FBSDKLoginKit'
        pod 'Kingfisher', '~> 4.0'
        pod ‘GeoFire’, :git => ‘https://github.com/firebase/geofire-objc.git'
end
